name: Hello World

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
         echo "Hello, World!"
         echo "How are you doing?"
         echo "`pwd`" > my_file
         more my_file
         echo "chicken=pie" >> $GITHUB_ENV

  do-more:
    runs-on: ubuntu-latest
    steps:
      - name: Access Env
        run: |
         echo "chicken=pie" >> $GITHUB_ENV
         echo $chicken