name: Hello World

on:
  workflow_dispatch:
    inputs:
     x:
      type: string
      default: foo

  push:
    branches:
      - main


  schedule:
    - cron: "22 2 * * *" # 03:00 UTC daily
    
env:
  MVENV: hehehe

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
         echo "Hello, World!"
         echo "How are you doing?"
         echo "`pwd`" > my_file
         more my_file
         echo "chicken=pie" >> $GITHUB_ENV

  do-more:
    runs-on: ubuntu-latest
    steps:
      - name: Access Env
        run: |       
         echo "chicken=pie" >> $GITHUB_ENV
         #export chicken=pie
      - name: show chicken
        run: |
         echo $chicken
         ls -a
         echo $GITHUB_ENV
         echo $MVENV

  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: print it
        run: echo ${{ inputs.x }}